<?php
// Database connection parameters
$host = 'localhost'; // Change this if your database is hosted elsewhere
$dbname = 'be_player_stats';
$username = 'root';
$password = '';

// Establish PDO connection
try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die("Database connection failed: " . $e->getMessage());
}


// Player data for Devin Carter
$players = [ 
    [
        'id' => 'PROG01',
        'first_name' => 'Devin',
        'last_name' => 'Carter',
        'three_point_percentage' => 37.7,
        'field_goal_percentage' => 47.3,
        'assists_per_game' => 3.6,
        'blocks_per_game' => 1.0,
        'steals_per_game' => 1.8,
        'turnovers_percentage' => 2.7,
        'rebounds_per_game' => 8.7,
        'free_throw_percentage' => 74.9,
    ],
    [
        'id' => 'PROG02',
        'first_name' => 'Ticket',
        'last_name' => 'Gaines',
        'three_point_percentage' => 30.4,
        'field_goal_percentage' => 39.5,
        'assists_per_game' => 1.1,
        'blocks_per_game' => 0.7,
        'steals_per_game' => 0.9,
        'turnovers_percentage' => 0.9,
        'rebounds_per_game' => 4.2,
        'free_throw_percentage' => 73.5,
    ],
    [
        'id' => 'PROG03',
        'first_name' => 'Jayden',
        'last_name' => 'Pierre',
        'three_point_percentage' => 36.6,
        'field_goal_percentage' => 40.2,
        'assists_per_game' => 3.2,
        'blocks_per_game' => 0.2,
        'steals_per_game' => 0.8,
        'turnovers_percentage' => 2.2,
        'rebounds_per_game' => 2.5,
        'free_throw_percentage' => 77.8,
    ],
    [
        'id' => 'PROC01',
        'first_name' => 'Josh',
        'last_name' => 'Oduro',
        'three_point_percentage' => 29.1,
        'field_goal_percentage' => 52.7,
        'assists_per_game' => 2.0,
        'blocks_per_game' => 1.3,
        'steals_per_game' => 0.9,
        'turnovers_percentage' => 2.1,
        'rebounds_per_game' => 7.5,
        'free_throw_percentage' => 81.9,
    ],
    [
        'id' => 'PROG04',
        'first_name' => 'Corey',
        'last_name' => 'Floyd Jr.',
        'three_point_percentage' => 24.7,
        'field_goal_percentage' => 34.1,
        'assists_per_game' => 1.2,
        'blocks_per_game' => 0.1,
        'steals_per_game' => 0.6,
        'turnovers_percentage' => 1.1,
        'rebounds_per_game' => 3.0,
        'free_throw_percentage' => 69.4,
    ],
    [
        'id' => 'PROG05',
        'first_name' => 'Garwey',
        'last_name' => 'Dual',
        'three_point_percentage' => 25.0,
        'field_goal_percentage' => 33.1,
        'assists_per_game' => 1.9,
        'blocks_per_game' => 0.7,
        'steals_per_game' => 0.8,
        'turnovers_percentage' => 1.0,
        'rebounds_per_game' => 1.3,
        'free_throw_percentage' => 66.7,
    ],
    [
        'id' => 'PROF01',
        'first_name' => 'Rich',
        'last_name' => 'Barron',
        'three_point_percentage' => 42.9,
        'field_goal_percentage' => 44.2,
        'assists_per_game' => 0.5,
        'blocks_per_game' => 0.2,
        'steals_per_game' => 0.3,
        'turnovers_percentage' => 0.5,
        'rebounds_per_game' => 1.4,
        'free_throw_percentage' => 57.1,
    ],
    [
        'id' => 'PROF02',
        'first_name' => 'Bryce',
        'last_name' => 'Hopkins',
        'three_point_percentage' => 18.9,
        'field_goal_percentage' => 42.9,
        'assists_per_game' => 1.4,
        'blocks_per_game' => 0.3,
        'steals_per_game' => 1.0,
        'turnovers_percentage' => 2.4,
        'rebounds_per_game' => 8.6,
        'free_throw_percentage' => 65.5,
    ],
    [
        'id' => 'PROC02',
        'first_name' => 'Rafael',
        'last_name' => 'Castro',
        'three_point_percentage' => 50.0,
        'field_goal_percentage' => 67.8,
        'assists_per_game' => 0.2,
        'blocks_per_game' => 0.4,
        'steals_per_game' => 0.3,
        'turnovers_percentage' => 0.5,
        'rebounds_per_game' => 2.4,
        'free_throw_percentage' => 41.9,
    ],
    [
        'id' => 'CREF01',
        'first_name' => 'Baylor',
        'last_name' => 'Scheierman',
        'three_point_percentage' => 38.1,
        'field_goal_percentage' => 44.8,
        'assists_per_game' => 3.9,
        'blocks_per_game' => 0.1,
        'steals_per_game' => 0.9,
        'turnovers_percentage' => 2.2,
        'rebounds_per_game' => 9.0,
        'free_throw_percentage' => 87.6,
    ],
    [
        'id' => 'CREG01',
        'first_name' => 'Trey',
        'last_name' => 'Alexander',
        'three_point_percentage' => 33.9,
        'field_goal_percentage' => 44.6,
        'assists_per_game' => 4.7,
        'blocks_per_game' => 0.4,
        'steals_per_game' => 1.1,
        'turnovers_percentage' => 2.5,
        'rebounds_per_game' => 5.7,
        'free_throw_percentage' => 82.4,
    ],
    [
        'id' => 'CREC01',
        'first_name' => 'Ryan',
        'last_name' => 'Kalkbrenner',
        'three_point_percentage' => 29.6,
        'field_goal_percentage' => 64.6,
        'assists_per_game' => 1.3,
        'blocks_per_game' => 3.1,
        'steals_per_game' => 0.4,
        'turnovers_percentage' => 1.5,
        'rebounds_per_game' => 7.6,
        'free_throw_percentage' => 71.1,
    ],
    [
        'id' => 'CREG02',
        'first_name' => 'Steven',
        'last_name' => 'Ashworth',
        'three_point_percentage' => 34.9,
        'field_goal_percentage' => 39.4,
        'assists_per_game' => 4.2,
        'blocks_per_game' => 0.0,
        'steals_per_game' => 0.5,
        'turnovers_percentage' => 1.5,
        'rebounds_per_game' => 3.3,
        'free_throw_percentage' => 90.7,
    ],
    [
        'id' => 'CREG03',
        'first_name' => 'Mason',
        'last_name' => 'Miller',
        'three_point_percentage' => 45.4,
        'field_goal_percentage' => 48.8,
        'assists_per_game' => 0.4,
        'blocks_per_game' => 0.1,
        'steals_per_game' => 0.2,
        'turnovers_percentage' => 0.4,
        'rebounds_per_game' => 3.3,
        'free_throw_percentage' => 72.2,
    ],
	[
		'id' => 'CREG04', 
		'first_name' => 'Francisco',
		'last_name' => 'Farabello',
		'three_point_percentage' => 42.0,
		'field_goal_percentage' => 49.5,
		'assists_per_game' => 1.5,
		'blocks_per_game' => 0.1,
		'steals_per_game' => 0.5,
		'turnovers_percentage' => 0.9,
		'rebounds_per_game' => 2.1,
		'free_throw_percentage' => 70.0,
	],

	[
		'id' => 'UCOG01', 
		'first_name' => 'Tristen',
		'last_name' => 'Newton',
		'three_point_percentage' => 32.1,
		'field_goal_percentage' => 41.5,
		'assists_per_game' => 6.2,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 0.9,
		'turnovers_percentage' => 2.5,
		'rebounds_per_game' => 6.6,
		'free_throw_percentage' => 80.8,
	],
	[
		'id' => 'UCOG02', 
		'first_name' => 'Cam',
		'last_name' => 'Spencer',
		'three_point_percentage' => 44.0,
		'field_goal_percentage' => 48.4,
		'assists_per_game' => 3.6,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 1.5,
		'turnovers_percentage' => 1.0,
		'rebounds_per_game' => 4.9,
		'free_throw_percentage' => 91.1,
	],
	[
		'id' => 'UCOF01', 
		'first_name' => 'Alex',
		'last_name' => 'Karaban',
		'three_point_percentage' => 37.9,
		'field_goal_percentage' => 49.5,
		'assists_per_game' => 1.5,
		'blocks_per_game' => 0.8,
		'steals_per_game' => 0.9,
		'turnovers_percentage' => 0.8,
		'rebounds_per_game' => 5.1,
		'free_throw_percentage' => 88.5,
	],
	[
		'id' => 'UCOG03', 
		'first_name' => 'Stephon',
		'last_name' => 'Castle',
		'three_point_percentage' => 26.7,
		'field_goal_percentage' => 47.2,
		'assists_per_game' => 2.9,
		'blocks_per_game' => 0.5,
		'steals_per_game' => 0.8,
		'turnovers_percentage' => 1.5,
		'rebounds_per_game' => 4.7,
		'free_throw_percentage' => 75.5,
	],

	[
		'id' => 'UCOC01', 
		'first_name' => 'Donovan',
		'last_name' => 'Clingan',
		'three_point_percentage' => 25.0,
		'field_goal_percentage' => 63.9,
		'assists_per_game' => 1.5,
		'blocks_per_game' => 2.5,
		'steals_per_game' => 0.5,
		'turnovers_percentage' => 0.8,
		'rebounds_per_game' => 7.4,
		'free_throw_percentage' => 58.3,
	],
	[
		'id' => 'UCOG04', 
		'first_name' => 'Hassan',
		'last_name' => 'Diarra',
		'three_point_percentage' => 35.7,
		'field_goal_percentage' => 48.3,
		'assists_per_game' => 2.4,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 0.8,
		'turnovers_percentage' => 1.1,
		'rebounds_per_game' => 3.0,
		'free_throw_percentage' => 70.0,
	],
	[
		'id' => 'UCOC02', 
		'first_name' => 'Samson',
		'last_name' => 'Johnson',
		'three_point_percentage' => 0.0,
		'field_goal_percentage' => 43.2,
		'assists_per_game' => 0.5,
		'blocks_per_game' => 0.9,
		'steals_per_game' => 0.4,
		'turnovers_percentage' => 0.8,
		'rebounds_per_game' => 2.8,
		'free_throw_percentage' => 43.8,
	],
	[
		'id' => 'UCOG05', 
		'first_name' => 'Solomon',
		'last_name' => 'Ball',
		'three_point_percentage' => 31.9,
		'field_goal_percentage' => 38.5,
		'assists_per_game' => 0.3,
		'blocks_per_game' => 0.0,
		'steals_per_game' => 0.2,
		'turnovers_percentage' => 0.4,
		'rebounds_per_game' => 1.0,
		'free_throw_percentage' => 69.6,
	],
	[
		'id' => 'VILC01', 
		'first_name' => 'Eric',
		'last_name' => 'Dixon',
		'three_point_percentage' => 34.6,
		'field_goal_percentage' => 46.5,
		'assists_per_game' => 1.7,
		'blocks_per_game' => 0.4,
		'steals_per_game' => 0.8,
		'turnovers_percentage' => 1.8,
		'rebounds_per_game' => 6.5,
		'free_throw_percentage' => 86.2,
	],
	[
		'id' => 'VILG01', 
		'first_name' => 'Justin',
		'last_name' => 'Moore',
		'three_point_percentage' => 31.2,
		'field_goal_percentage' => 38.4,
		'assists_per_game' => 2.2,
		'blocks_per_game' => 0.4,
		'steals_per_game' => 0.6,
		'turnovers_percentage' => 0.9,
		'rebounds_per_game' => 3.6,
		'free_throw_percentage' => 86.4,
	],
	[
		'id' => 'VILG02', 
		'first_name' => 'TJ',
		'last_name' => 'Bamba',
		'three_point_percentage' => 36.9,
		'field_goal_percentage' => 43.0,
		'assists_per_game' => 1.8,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 0.8,
		'turnovers_percentage' => 1.4,
		'rebounds_per_game' => 3.6,
		'free_throw_percentage' => 82.4,
	],
	[
		'id' => 'VILF01', 
		'first_name' => 'Tyler',
		'last_name' => 'Burton',
		'three_point_percentage' => 32.7,
		'field_goal_percentage' => 40.1,
		'assists_per_game' => 1.0,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 0.7,
		'turnovers_percentage' => 0.5,
		'rebounds_per_game' => 6.1,
		'free_throw_percentage' => 75.0,
	],
	[
		'id' => 'VILG03', 
		'first_name' => 'Mark',
		'last_name' => 'Armstrong',
		'three_point_percentage' => 28.2,
		'field_goal_percentage' => 41.7,
		'assists_per_game' => 2.4,
		'blocks_per_game' => 0.2,
		'steals_per_game' => 0.9,
		'turnovers_percentage' => 1.7,
		'rebounds_per_game' => 2.3,
		'free_throw_percentage' => 77.6,
	],
	[
		'id' => 'VILG04', 
		'first_name' => 'Hakim',
		'last_name' => 'Hart',
		'three_point_percentage' => 32.9,
		'field_goal_percentage' => 46.4,
		'assists_per_game' => 1.6,
		'blocks_per_game' => 0.1,
		'steals_per_game' => 0.8,
		'turnovers_percentage' => 0.9,
		'rebounds_per_game' => 3.2,
		'free_throw_percentage' => 79.5,
	],
	[
		'id' => 'VILG05', 
		'first_name' => 'Jordan',
		'last_name' => 'Longino',
		'three_point_percentage' => 32.5,
		'field_goal_percentage' => 40.9,
		'assists_per_game' => 1.5,
		'blocks_per_game' => 0.2,
		'steals_per_game' => 0.8,
		'turnovers_percentage' => 1.0,
		'rebounds_per_game' => 2.5,
		'free_throw_percentage' => 83.3,
	],
	[
		'id' => 'VILG06', 
		'first_name' => 'Brendan',
		'last_name' => 'Hausen',
		'three_point_percentage' => 38.1,
		'field_goal_percentage' => 39.2,
		'assists_per_game' => 0.5,
		'blocks_per_game' => 0.0,
		'steals_per_game' => 0.4,
		'turnovers_percentage' => 0.6,
		'rebounds_per_game' => 1.6,
		'free_throw_percentage' => 86.7,
	],
	[
		'id' => 'VILF02', 
		'first_name' => 'Lance',
		'last_name' => 'Ware',
		'three_point_percentage' => 0.0,
		'field_goal_percentage' => 48.3,
		'assists_per_game' => 0.5,
		'blocks_per_game' => 0.4,
		'steals_per_game' => 0.2,
		'turnovers_percentage' => 0.5,
		'rebounds_per_game' => 2.3,
		'free_throw_percentage' => 55.6,
	],
	[
		'id' => 'DEPG01', 
		'first_name' => 'Chico',
		'last_name' => 'Carter Jr.',
		'three_point_percentage' => 35.8,
		'field_goal_percentage' => 39.4,
		'assists_per_game' => 3.7,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 0.7,
		'turnovers_percentage' => 2.2,
		'rebounds_per_game' => 2.8,
		'free_throw_percentage' => 76.9,
	],
	[
		'id' => 'DEPG02', 
		'first_name' => 'Elijah',
		'last_name' => 'Fisher',
		'three_point_percentage' => 26.3,
		'field_goal_percentage' => 52.0,
		'assists_per_game' => 1.4,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 0.8,
		'turnovers_percentage' => 1.6,
		'rebounds_per_game' => 3.8,
		'free_throw_percentage' => 72.2,
	],
	[
		'id' => 'DEPF01', 
		'first_name' => 'Jeremiah',
		'last_name' => 'Oden',
		'three_point_percentage' => 31.3,
		'field_goal_percentage' => 34.7,
		'assists_per_game' => 0.7,
		'blocks_per_game' => 0.4,
		'steals_per_game' => 0.4,
		'turnovers_percentage' => 1.2,
		'rebounds_per_game' => 3.2,
		'free_throw_percentage' => 81.4,
	],
	[
		'id' => 'DEPG03', 
		'first_name' => 'Jalen',
		'last_name' => 'Terry',
		'three_point_percentage' => 45.2,
		'field_goal_percentage' => 41.7,
		'assists_per_game' => 2.5,
		'blocks_per_game' => 0.1,
		'steals_per_game' => 1.0,
		'turnovers_percentage' => 2.1,
		'rebounds_per_game' => 4.0,
		'free_throw_percentage' => 85.7,
	],
	[
		'id' => 'DEPG04', 
		'first_name' => 'Jaden',
		'last_name' => 'Henley',
		'three_point_percentage' => 26.9,
		'field_goal_percentage' => 43.6,
		'assists_per_game' => 1.3,
		'blocks_per_game' => 0.2,
		'steals_per_game' => 0.9,
		'turnovers_percentage' => 1.8,
		'rebounds_per_game' => 2.7,
		'free_throw_percentage' => 75.5,
	],
	[
		'id' => 'DEPF02', 
		'first_name' => 'DaSean',
		'last_name' => 'Nelson',
		'three_point_percentage' => 28.3,
		'field_goal_percentage' => 46.2,
		'assists_per_game' => 1.9,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 0.4,
		'turnovers_percentage' => 1.7,
		'rebounds_per_game' => 3.5,
		'free_throw_percentage' => 72.2,
	],
	[
		'id' => 'DEPG05', 
		'first_name' => 'Caleb',
		'last_name' => 'Murphy',
		'three_point_percentage' => 0.0,
		'field_goal_percentage' => 53.3,
		'assists_per_game' => 1.8,
		'blocks_per_game' => 0.3,
		'steals_per_game' => 0.8,
		'turnovers_percentage' => 1.8,
		'rebounds_per_game' => 2.4,
		'free_throw_percentage' => 76.5,
	],
	[
		'id' => 'DEPG06', 
		'first_name' => 'K.T.',
		'last_name' => 'Raimey',
		'three_point_percentage' => 36.3,
		'field_goal_percentage' => 35.5,
		'assists_per_game' => 1.2,
		'blocks_per_game' => 0.4,
		'steals_per_game' => 0.6,
		'turnovers_percentage' => 1.3,
		'rebounds_per_game' => 2.0,
		'free_throw_percentage' => 87.5,
	],
	[
		'id' => 'DEPC01', 
		'first_name' => 'Churchill',
		'last_name' => 'Abass',
		'three_point_percentage' => 0.0,
		'field_goal_percentage' => 57.8,
		'assists_per_game' => 0.2,
		'blocks_per_game' => 0.9,
		'steals_per_game' => 0.6,
		'turnovers_percentage' => 1.1,
		'rebounds_per_game' => 3.5,
		'free_throw_percentage' => 45.8,
	],
	[
		'id' => 'SETG01', 
		'first_name' => 'Al-Amir',
		'last_name' => 'Dawes',
		'three_point_percentage' => 38.9,
		'field_goal_percentage' => 41.9,
		'assists_per_game' => 2.3,
		'blocks_per_game' => 0.1,
		'steals_per_game' => 1.2,
		'turnovers_percentage' => 1.9,
		'rebounds_per_game' => 2.8,
		'free_throw_percentage' => 93.5,
	],
	[
		'id' => 'SETG02', 
		'first_name' => 'Dre',
		'last_name' => 'Davis',
		'rebounds_per_game' => 5.9,
		'assists_per_game' => 1.6,
		'steals_per_game' => 0.9,
		'blocks_per_game' => 1.3,
		'turnovers_percentage' => 1.5,
		'field_goal_percentage' => 49.2,
		'free_throw_percentage' => 84.0,
		'three_point_percentage' => 35.0,
	],
	[
		'id' => 'SETG03', 
		'first_name' => 'Kadary',
		'last_name' => 'Richmond',
		'rebounds_per_game' => 7.0,
		'assists_per_game' => 5.1,
		'steals_per_game' => 2.2,
		'blocks_per_game' => 0.6,
		'turnovers_percentage' => 3.1,
		'field_goal_percentage' => 44.1,
		'free_throw_percentage' => 80.7,
		'three_point_percentage' => 27.0,
	],
	[
		'id' => 'SETG04', 
		'first_name' => 'Dylan',
		'last_name' => 'Addae-Wusu',
		'rebounds_per_game' => 5.3,
		'assists_per_game' => 2.2,
		'steals_per_game' => 1.6,
		'blocks_per_game' => 0.4,
		'turnovers_percentage' => 1.8,
		'field_goal_percentage' => 35.6,
		'free_throw_percentage' => 66.7,
		'three_point_percentage' => 29.0,
	],
	[
		'id' => 'SETC01', 
		'first_name' => 'Jaden',
		'last_name' => 'Bediako',
		'rebounds_per_game' => 6.9,
		'assists_per_game' => 0.4,
		'steals_per_game' => 0.5,
		'blocks_per_game' => 1.6,
		'turnovers_percentage' => 1.2,
		'field_goal_percentage' => 61.0,
		'free_throw_percentage' => 65.5,
		'three_point_percentage' => 0.0,
	],
	[
		'id' => 'SETG05', 
		'first_name' => 'Isaiah',
		'last_name' => 'Coleman',
		'rebounds_per_game' => 2.6,
		'assists_per_game' => 0.5,
		'steals_per_game' => 0.8,
		'blocks_per_game' => 0.3,
		'turnovers_percentage' => 0.9,
		'field_goal_percentage' => 47.5,
		'free_throw_percentage' => 71.7,
		'three_point_percentage' => 31.1,
	],
	[
		'id' => 'SETC02', 
		'first_name' => 'Elijah',
		'last_name' => 'Hutchins-Everett',
		'rebounds_per_game' => 2.5,
		'assists_per_game' => 0.3,
		'steals_per_game' => 0.4,
		'blocks_per_game' => 0.5,
		'turnovers_percentage' => 0.7,
		'field_goal_percentage' => 48.6,
		'free_throw_percentage' => 80.5,
		'three_point_percentage' => 28.6,
	],
	[
		'id' => 'SETG06', 
		'first_name' => 'Jaquan',
		'last_name' => 'Sanders',
		'rebounds_per_game' => 0.9,
		'assists_per_game' => 0.4,
		'steals_per_game' => 0.2,
		'blocks_per_game' => 0.2,
		'turnovers_percentage' => 0.4,
		'field_goal_percentage' => 44.4,
		'free_throw_percentage' => 66.7,
		'three_point_percentage' => 37.3,
	],
	[
		'id' => 'XAVG01', 
		'first_name' => 'Dayvion',
		'last_name' => 'McKnight',
		'rebounds_per_game' => 3.7,
		'assists_per_game' => 4.8,
		'steals_per_game' => 1.5,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 1.6,
		'field_goal_percentage' => 46.7,
		'free_throw_percentage' => 81.3,
		'three_point_percentage' => 37.2,
	],
	[
		'id' => 'XAVG02', 
		'first_name' => 'Desmond',
		'last_name' => 'Claude',
		'rebounds_per_game' => 4,2,
		'assists_per_game' => 4.2,
		'steals_per_game' => 1.1,
		'blocks_per_game' => 0.3,
		'turnovers_percentage' => 2.2,
		'field_goal_percentage' => 42.6,
		'free_throw_percentage' => 79.4,
		'three_point_percentage' => 23.9,
	],
	[
		'id' => 'XAVG03', 
		'first_name' => 'Quincy',
		'last_name' => 'Olivari',
		'rebounds_per_game' => 5.6,
		'assists_per_game' => 2.1,
		'steals_per_game' => 1.4,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 1.6,
		'field_goal_percentage' => 42.5,
		'free_throw_percentage' => 81.4,
		'three_point_percentage' => 40.9,
	],
	[
		'id' => 'XAVF01', 
		'first_name' => 'Abou',
		'last_name' => 'Ousmane',
		'rebounds_per_game' => 6.4,
		'assists_per_game' => 1.3,
		'steals_per_game' => 0.7,
		'blocks_per_game' => 1.2,
		'turnovers_percentage' => 1.5,
		'field_goal_percentage' => 46.5,
		'free_throw_percentage' => 45.0,
		'three_point_percentage' => 25.0,
	],
	[
		'id' => 'XAVG04', 
		'first_name' => 'Dailyn',
		'last_name' => 'Swain',
		'rebounds_per_game' => 3.0,
		'assists_per_game' => 1.2,
		'steals_per_game' => 1.0,
		'blocks_per_game' => 0.7,
		'turnovers_percentage' => 0.7,
		'field_goal_percentage' => 45.9,
		'free_throw_percentage' => 81.3,
		'three_point_percentage' => 15.4,
	],
	[
		'id' => 'XAVF02', 
		'first_name' => 'Gytis',
		'last_name' => 'Nemeiksa',
		'rebounds_per_game' => 4.2,
		'assists_per_game' => 0.9,
		'steals_per_game' => 0.2,
		'blocks_per_game' => 0.4,
		'turnovers_percentage' => 1.0,
		'field_goal_percentage' => 46.9,
		'free_throw_percentage' => 64.7,
		'three_point_percentage' => 36.4,
	],
	[
		'id' => 'XAVF03', 
		'first_name' => 'Lazar',
		'last_name' => 'Djokovic',
		'rebounds_per_game' => 2.9,
		'assists_per_game' => 0.9,
		'steals_per_game' => 0.2,
		'blocks_per_game' => 0.3,
		'turnovers_percentage' => 1.0,
		'field_goal_percentage' => 30.0,
		'free_throw_percentage' => 65.0,
		'three_point_percentage' => 25.0,
	],
	[
		'id' => 'XAVG05', 
		'first_name' => 'Trey',
		'last_name' => 'Greem',
		'rebounds_per_game' => 1.0,
		'assists_per_game' => 1.1,
		'steals_per_game' => 0.6,
		'blocks_per_game' => 0.0,
		'turnovers_percentage' => 1.2,
		'field_goal_percentage' => 35.9,
		'free_throw_percentage' => 94.7,
		'three_point_percentage' => 32.2,
	],
	[
		'id' => 'XAVF04', 
		'first_name' => 'Sasa',
		'last_name' => 'Ciani',
		'rebounds_per_game' => 2.9,
		'assists_per_game' => 0.8,
		'steals_per_game' => 0.3,
		'blocks_per_game' => 0.3,
		'turnovers_percentage' => 0.5,
		'field_goal_percentage' => 48.5,
		'free_throw_percentage' => 52.4,
		'three_point_percentage' => 0.0,
	],
	[
		'id' => 'XAVC01', 
		'first_name' => 'Kachi',
		'last_name' => 'Nzeh',
		'rebounds_per_game' => 2.5,
		'assists_per_game' => 0.4,
		'steals_per_game' => 0.3,
		'blocks_per_game' => 0.4,
		'turnovers_percentage' => 0.6,
		'field_goal_percentage' => 60.0,
		'free_throw_percentage' => 55.0,
		'three_point_percentage' => 0.0,
	],
	[
		'id' => 'MARG01', 
		'first_name' => 'Tyler',
		'last_name' => 'Kolek',
		'rebounds_per_game' => 4.9,
		'assists_per_game' => 7.7,
		'steals_per_game' => 1.6,
		'blocks_per_game' => 0.2,
		'turnovers_percentage' => 2.9,
		'field_goal_percentage' => 49.6,
		'free_throw_percentage' => 85.1,
		'three_point_percentage' => 38.8,
	],
	[
		'id' => 'MARC01', 
		'first_name' => 'Oso',
		'last_name' => 'Ighodaro',
		'rebounds_per_game' => 6.9,
		'assists_per_game' => 2.9,
		'steals_per_game' => 1.1,
		'blocks_per_game' => 1.3,
		'turnovers_percentage' => 1.8,
		'field_goal_percentage' => 57.6,
		'free_throw_percentage' => 62.3,
		'three_point_percentage' => 0.0,
	],
	[
		'id' => 'MARG02', 
		'first_name' => 'Kam',
		'last_name' => 'Jones',
		'rebounds_per_game' => 17.2,
		'assists_per_game' => 2.9,
		'steals_per_game' => 1.1,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 1.4,
		'field_goal_percentage' => 50.1,
		'free_throw_percentage' => 72.4,
		'three_point_percentage' => 40.6,
	],
	[
		'id' => 'MARF01', 
		'first_name' => 'David',
		'last_name' => 'Joplin',
		'rebounds_per_game' => 3.9,
		'assists_per_game' => 0.6,
		'steals_per_game' => 0.8,
		'blocks_per_game' => 0.9,
		'turnovers_percentage' => 1.2,
		'field_goal_percentage' => 41.3,
		'free_throw_percentage' => 68.1,
		'three_point_percentage' => 35.5,
	],
	[
		'id' => 'MARG03', 
		'first_name' => 'Stevie',
		'last_name' => 'Mitchell',
		'rebounds_per_game' => 4.1,
		'assists_per_game' => 0.8,
		'steals_per_game' => 1.9,
		'blocks_per_game' => 0.2,
		'turnovers_percentage' => 0.8,
		'field_goal_percentage' => 51.6,
		'free_throw_percentage' => 76.6,
		'three_point_percentage' => 26.5,
	],
	[
		'id' => 'MARG04', 
		'first_name' => 'Chase',
		'last_name' => 'Ross',
		'rebounds_per_game' => 3.1,
		'assists_per_game' => 0.7,
		'steals_per_game' => 1.3,
		'blocks_per_game' => 0.4,
		'turnovers_percentage' => 0.8,
		'field_goal_percentage' => 42.5,
		'free_throw_percentage' => 71.9,
		'three_point_percentage' => 36.2,
	],
	[
		'id' => 'MARF02', 
		'first_name' => 'Ben',
		'last_name' => 'Gold',
		'rebounds_per_game' => 3.0,
		'assists_per_game' => 0.6,
		'steals_per_game' => 0.4,
		'blocks_per_game' => 0.4,
		'turnovers_percentage' => 0.5,
		'field_goal_percentage' => 44.7,
		'free_throw_percentage' => 52.9,
		'three_point_percentage' => 35.9,
	],
	[
		'id' => 'MARG05', 
		'first_name' => 'Sean',
		'last_name' => 'Jones',
		'rebounds_per_game' => 1.5,
		'assists_per_game' => 2.0,
		'steals_per_game' => 0.9,
		'blocks_per_game' => 0.0,
		'turnovers_percentage' => 1.1,
		'field_goal_percentage' => 41.8,
		'free_throw_percentage' => 75.0,
		'three_point_percentage' => 25.7,
	],
	[
		'id' => 'XAVG01', 
		'first_name' => 'Dayvion',
		'last_name' => 'McKnight',
		'rebounds_per_game' => 3.7,
		'assists_per_game' => 4.8,
		'steals_per_game' => 1.5,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 1.6,
		'field_goal_percentage' => 46.7,
		'free_throw_percentage' => 81.3,
		'three_point_percentage' => 37.2,
	],
	[
		'id' => 'BUTG01', 
		'first_name' => 'Jahmyl',
		'last_name' => 'Telfort',
		'rebounds_per_game' => 4.9,
		'assists_per_game' => 3.0,
		'steals_per_game' => 1.0,
		'blocks_per_game' => 0.5,
		'turnovers_percentage' => 1.7,
		'field_goal_percentage' => 43.5,
		'free_throw_percentage' => 84.6,
		'three_point_percentage' => 32.7,
	],
	[
		'id' => 'BUTG02', 
		'first_name' => 'Pierre',
		'last_name' => 'Brooks',
		'rebounds_per_game' => 4.0,
		'assists_per_game' => 1.1,
		'steals_per_game' => 0.5,
		'blocks_per_game' => 0.2,
		'turnovers_percentage' => 1.5,
		'field_goal_percentage' => 45.6,
		'free_throw_percentage' => 69.2,
		'three_point_percentage' => 40.6,
	],
	[
		'id' => 'BUTG03', 
		'first_name' => 'Posh',
		'last_name' => 'Alexander',
		'rebounds_per_game' => 4.6,
		'assists_per_game' => 4.9,
		'steals_per_game' => 2.2,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 2.8,
		'field_goal_percentage' => 43.2,
		'free_throw_percentage' => 78.1,
		'three_point_percentage' => 33.3,
	],
	[
		'id' => 'BUTG04', 
		'first_name' => 'DJ',
		'last_name' => 'Davis',
		'rebounds_per_game' => 3.2,
		'assists_per_game' => 2.6,
		'steals_per_game' => 1.1,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 1.6,
		'field_goal_percentage' => 42.9,
		'free_throw_percentage' => 95.0,
		'three_point_percentage' => 35.1,
	],
	[
		'id' => 'BUTF01', 
		'first_name' => 'Jalen',
		'last_name' => 'Thomas',
		'rebounds_per_game' => 6.2,
		'assists_per_game' => 0.8,
		'steals_per_game' => 0.4,
		'blocks_per_game' => 1.2,
		'turnovers_percentage' => 0.8,
		'field_goal_percentage' => 55.7,
		'free_throw_percentage' => 78.0,
		'three_point_percentage' => 32.0,
	],
	[
		'id' => 'BUTG05', 
		'first_name' => 'Landon',
		'last_name' => 'Moore',
		'rebounds_per_game' => 1.3,
		'assists_per_game' => 1.3,
		'steals_per_game' => 0.4,
		'blocks_per_game' => 0.0,
		'turnovers_percentage' => 0.8,
		'field_goal_percentage' => 38.1,
		'free_throw_percentage' => 75.8,
		'three_point_percentage' => 37.3,
	],
	[
		'id' => 'BUTG06', 
		'first_name' => 'Finley',
		'last_name' => 'Bizjack',
		'rebounds_per_game' => 1.2,
		'assists_per_game' => 0.9,
		'steals_per_game' => 0.3,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 0.5,
		'field_goal_percentage' => 38.3,
		'free_throw_percentage' => 78.8,
		'three_point_percentage' => 27.0,
	],
	[
		'id' => 'BUTC01', 
		'first_name' => 'Andre',
		'last_name' => 'Screen',
		'rebounds_per_game' => 4.5,
		'assists_per_game' => 0.4,
		'steals_per_game' => 0.1,
		'blocks_per_game' => 0.5,
		'turnovers_percentage' => 0.6,
		'field_goal_percentage' => 58.0,
		'free_throw_percentage' => 59.3,
		'three_point_percentage' => 0.0,
	],
	[
		'id' => 'BUTF02', 
		'first_name' => 'Connor',
		'last_name' => 'Turnbull',
		'rebounds_per_game' => 2.2,
		'assists_per_game' => 0.2,
		'steals_per_game' => 0.6,
		'blocks_per_game' => 1.8,
		'turnovers_percentage' => 0.3,
		'field_goal_percentage' => 51.9,
		'free_throw_percentage' => 100.0,
		'three_point_percentage' => 42.9,
	],
	[
		'id' => 'GEOG01', 
		'first_name' => 'Jayden',
		'last_name' => 'Epps',
		'rebounds_per_game' => 2.9,
		'assists_per_game' => 4.2,
		'steals_per_game' => 1.2,
		'blocks_per_game' => 0.4,
		'turnovers_percentage' => 3.4,
		'field_goal_percentage' => 39.2,
		'free_throw_percentage' => 76.3,
		'three_point_percentage' => 30.5,
	],
	[
		'id' => 'GEOG02', 
		'first_name' => 'Dontrez',
		'last_name' => 'Styles',
		'rebounds_per_game' => 5.8,
		'assists_per_game' => 0.8,
		'steals_per_game' => 0.6,
		'blocks_per_game' => 0.7,
		'turnovers_percentage' => 1.5,
		'field_goal_percentage' => 43.0,
		'free_throw_percentage' => 77.6,
		'three_point_percentage' => 36.8,
	],
	[
		'id' => 'GEOG03', 
		'first_name' => 'Jay',
		'last_name' => 'Heath',
		'rebounds_per_game' => 2.8,
		'assists_per_game' => 1.9,
		'steals_per_game' => 0.7,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 1.3,
		'field_goal_percentage' => 35.9,
		'free_throw_percentage' => 70.5,
		'three_point_percentage' => 37.2,
	],
	[
		'id' => 'GEOF01', 
		'first_name' => 'Supreme',
		'last_name' => 'Cook',
		'rebounds_per_game' => 8.0,
		'assists_per_game' => 0.6,
		'steals_per_game' => 0.8,
		'blocks_per_game' => 0.5,
		'turnovers_percentage' => 1.5,
		'field_goal_percentage' => 57.5,
		'free_throw_percentage' => 57.1,
		'three_point_percentage' => 0.0,
	],
	[
		'id' => 'GEOF02', 
		'first_name' => 'Ismael',
		'last_name' => 'Massoud',
		'rebounds_per_game' => 3.0,
		'assists_per_game' => 0.5,
		'steals_per_game' => 0.5,
		'blocks_per_game' => 0.4,
		'turnovers_percentage' => 1.0,
		'field_goal_percentage' => 30.1,
		'free_throw_percentage' => 92.0,
		'three_point_percentage' => 31.9,
	],
	[
		'id' => 'GEOG04', 
		'first_name' => 'Rowan',
		'last_name' => 'Brumbaugh',
		'rebounds_per_game' => 2.2,
		'assists_per_game' => 2.6,
		'steals_per_game' => 0.9,
		'blocks_per_game' => 0.0,
		'turnovers_percentage' => 2.0,
		'field_goal_percentage' => 40.7,
		'free_throw_percentage' => 78.9,
		'three_point_percentage' => 37.0,
	],
	[
		'id' => 'GEOG05', 
		'first_name' => 'Wayne',
		'last_name' => 'Bristol Jr.',
		'rebounds_per_game' => 3.3,
		'assists_per_game' => 0.8,
		'steals_per_game' => 0.9,
		'blocks_per_game' => 0.4,
		'turnovers_percentage' => 0.6,
		'field_goal_percentage' => 36.4,
		'free_throw_percentage' => 73.5,
		'three_point_percentage' => 30.2,
	],
	[
		'id' => 'GEOC01', 
		'first_name' => 'Drew',
		'last_name' => 'Fielder',
		'rebounds_per_game' => 3.1,
		'assists_per_game' => 0.7,
		'steals_per_game' => 0.3,
		'blocks_per_game' => 0.6,
		'turnovers_percentage' => 0.4,
		'field_goal_percentage' => 48.4,
		'free_throw_percentage' => 62.9,
		'three_point_percentage' => 40.7,
	],
	[
		'id' => 'STJG01', 
		'first_name' => 'Daniss',
		'last_name' => 'Jenkins',
		'rebounds_per_game' => 3.5,
		'assists_per_game' => 5.4,
		'steals_per_game' => 1.6,
		'blocks_per_game' => 0.5,
		'turnovers_percentage' => 2.4,
		'field_goal_percentage' => 44.6,
		'free_throw_percentage' => 85.1,
		'three_point_percentage' => 35.4,
	],
	[
		'id' => 'STJG02', 
		'first_name' => 'Chris',
		'last_name' => 'Ledlum',
		'rebounds_per_game' => 6.9,
		'assists_per_game' => 1.8,
		'steals_per_game' => 1.4,
		'blocks_per_game' => 1.2,
		'turnovers_percentage' => 1.5,
		'field_goal_percentage' => 42.7,
		'free_throw_percentage' => 70.8,
		'three_point_percentage' => 31.5,
	],
	[
		'id' => 'STJC01', 
		'first_name' => 'Joel',
		'last_name' => 'Soriano',
		'rebounds_per_game' => 9.5,
		'assists_per_game' => 1.5,
		'steals_per_game' => 0.2,
		'blocks_per_game' => 1.7,
		'turnovers_percentage' => 1.2,
		'field_goal_percentage' => 57.7,
		'free_throw_percentage' => 70.2,
		'three_point_percentage' => 43.8,
	],
	[
		'id' => 'STJG03', 
		'first_name' => 'Jordan',
		'last_name' => 'Dingle',
		'rebounds_per_game' => 2.0,
		'assists_per_game' => 1.7,
		'steals_per_game' => 0.8,
		'blocks_per_game' => 0.1,
		'turnovers_percentage' => 1.3,
		'field_goal_percentage' => 44.0,
		'free_throw_percentage' => 74.5,
		'three_point_percentage' => 31.1,
	],
	[
		'id' => 'STJG04', 
		'first_name' => 'RJ',
		'last_name' => 'Luis Jr.',
		'rebounds_per_game' => 4.6,
		'assists_per_game' => 1.0,
		'steals_per_game' => 1.2,
		'blocks_per_game' => 0.3,
		'turnovers_percentage' => 1.3,
		'field_goal_percentage' => 42.2,
		'free_throw_percentage' => 75.0,
		'three_point_percentage' => 20.0,
	],
	[
		'id' => 'STJG05', 
		'first_name' => 'Nahiem',
		'last_name' => 'Alleyne',
		'rebounds_per_game' => 1.6,
		'assists_per_game' => 1.0,
		'steals_per_game' => 0.3,
		'blocks_per_game' => 0.0,
		'turnovers_percentage' => 0.6,
		'field_goal_percentage' => 43.8,
		'free_throw_percentage' => 91.3,
		'three_point_percentage' => 38.0,
	],
	[
		'id' => 'STJF01', 
		'first_name' => 'Glem',
		'last_name' => 'Taylor Jr.',
		'rebounds_per_game' => 2.2,
		'assists_per_game' => 1.2,
		'steals_per_game' => 0.8,
		'blocks_per_game' => 0.2,
		'turnovers_percentage' => 0.8,
		'field_goal_percentage' => 44.9,
		'free_throw_percentage' => 69.7,
		'three_point_percentage' => 42.4,
	],
	[
		'id' => 'STJF02', 
		'first_name' => 'Brady',
		'last_name' => 'Dunlap',
		'rebounds_per_game' => 1.5,
		'assists_per_game' => 0.2,
		'steals_per_game' => 0.3,
		'blocks_per_game' => 0.2,
		'turnovers_percentage' => 0.4,
		'field_goal_percentage' => 38.0,
		'free_throw_percentage' => 41.7,
		'three_point_percentage' => 30.6,
	],
	[
		'id' => 'STJF03', 
		'first_name' => 'Zuby',
		'last_name' => 'Ejiofor',
		'rebounds_per_game' => 3.1,
		'assists_per_game' => 0.7,
		'steals_per_game' => 0.4,
		'blocks_per_game' => 1.1,
		'turnovers_percentage' => 0.6,
		'field_goal_percentage' => 48.9,
		'free_throw_percentage' => 71.2,
		'three_point_percentage' => 37.5,
	],
	 [
        'id' => 'AVGG01', 
        'first_name' => 'Average',
        'last_name' => 'Gaured',
        'rebounds_per_game' => 3.7,
        'assists_per_game' => 2.3,
        'steals_per_game' => 0.9,
        'blocks_per_game' => 0.3,
        'turnovers_percentage' => 1.5,
        'field_goal_percentage' => 43.0,
        'free_throw_percentage' => 78.5,
        'three_point_percentage' => 32.8,
    ],
    [
        'id' => 'AVGF01', 
        'first_name' => 'Average',
        'last_name' => 'Forward',
        'rebounds_per_game' => 4.2,
        'assists_per_game' => 1.0,
        'steals_per_game' => 0.5,
        'blocks_per_game' => 0.6,
        'turnovers_percentage' => 1.0,
        'field_goal_percentage' => 44.6,
        'free_throw_percentage' => 68.6,
        'three_point_percentage' => 28.8,
    ],
    [
        'id' => 'AVGC01', 
        'first_name' => 'Average',
        'last_name' => 'Center',
        'rebounds_per_game' => 5.3,
        'assists_per_game' => 1.0,
        'steals_per_game' => 0.5,
        'blocks_per_game' => 1.2,
        'turnovers_percentage' => 1.1,
        'field_goal_percentage' => 56.3,
        'free_throw_percentage' => 63.2,
        'three_point_percentage' => 20.1,
    ]
];

// Insert player data into the database
foreach ($players as $player) {
    try {
        // Check if the player already exists
        $checkStmt = $pdo->prepare("SELECT COUNT(*) FROM players WHERE id = :id");
        $checkStmt->bindParam(':id', $player['id']);
        $checkStmt->execute();
        $exists = $checkStmt->fetchColumn();

        if (!$exists) {
            // Prepare SQL statement to insert player
            $stmt = $pdo->prepare("
                INSERT INTO players (
                    id, first_name, last_name, three_point_percentage, field_goal_percentage, assists_per_game, blocks_per_game, steals_per_game, turnovers_percentage, rebounds_per_game, free_throw_percentage
                ) VALUES (
                    :id, :first_name, :last_name, :three_point_percentage, :field_goal_percentage, :assists_per_game, :blocks_per_game, :steals_per_game, :turnovers_percentage, :rebounds_per_game, :free_throw_percentage
                )
            ");

            // Bind parameters
            $stmt->bindParam(':id', $player['id']);
            $stmt->bindParam(':first_name', $player['first_name']);
            $stmt->bindParam(':last_name', $player['last_name']);
            $stmt->bindParam(':three_point_percentage', $player['three_point_percentage']);
            $stmt->bindParam(':field_goal_percentage', $player['field_goal_percentage']);
            $stmt->bindParam(':assists_per_game', $player['assists_per_game']);
            $stmt->bindParam(':blocks_per_game', $player['blocks_per_game']);
            $stmt->bindParam(':steals_per_game', $player['steals_per_game']);
            $stmt->bindParam(':turnovers_percentage', $player['turnovers_percentage']);
            $stmt->bindParam(':rebounds_per_game', $player['rebounds_per_game']);
            $stmt->bindParam(':free_throw_percentage', $player['free_throw_percentage']);

            // Execute the statement
            $stmt->execute();
            echo "Inserted player {$player['first_name']} {$player['last_name']} successfully.<br>";
        } else {
            echo "Player with ID {$player['id']} already exists.<br>";
        }
    } catch (PDOException $e) {
        echo "Error inserting player {$player['first_name']} {$player['last_name']}: " . $e->getMessage() . "<br>";
    }
}

// Query to fetch Providence Basketball Players with IDs starting with 'PRO'
$query = "SELECT * FROM players WHERE id LIKE 'PRO%'";
$stmt = $pdo->prepare($query);
$stmt->execute();
$players = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Close the connection
$pdo = null;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Providence Basketball Players</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Providence Basketball Players</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Three-Point Percentage</th>
                <th>Field Goal Percentage</th>
                <th>Assists Per Game</th>
                <th>Blocks Per Game</th>
                <th>Steals Per Game</th>
                <th>Turnovers Percentage</th>
                <th>Rebounds Per Game</th>
                <th>Free Throw Percentage</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($players as $player): ?>
                <tr>
                    <td><?php echo htmlspecialchars($player['id']); ?></td>
                    <td><?php echo htmlspecialchars($player['first_name']); ?></td>
                    <td><?php echo htmlspecialchars($player['last_name']); ?></td>
                    <td><?php echo htmlspecialchars($player['three_point_percentage']); ?></td>
                    <td><?php echo htmlspecialchars($player['field_goal_percentage']); ?></td>
                    <td><?php echo htmlspecialchars($player['assists_per_game']); ?></td>
                    <td><?php echo htmlspecialchars($player['blocks_per_game']); ?></td>
                    <td><?php echo htmlspecialchars($player['steals_per_game']); ?></td>
                    <td><?php echo htmlspecialchars($player['turnovers_percentage']); ?></td>
                    <td><?php echo htmlspecialchars($player['rebounds_per_game']); ?></td>
                    <td><?php echo htmlspecialchars($player['free_throw_percentage']); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>
</html>